**ID -202218061**

**NAME- JATAN SAHU**

**ASSIGNMENT - 04**

#Write a program to convert primal to dual for slack variable

In [ ]:
import numpy as np
#Taking the coefficients of the primal problem (c, A, b)
x_prim = int(input("Enter number of constraint in primal problem :"))

c_prim=np.array(list(map(int,input("Enter coefficients of the objective function :").split(" "))))


#Taking input for constraints
A= []
for i in range(x_prim):
  a=list(map(int,input(f"Enter constrain{i+1} seprated with spaces :").split(" ")))
  A.append(a)
A_prim =np.array(A)
# A_prim=[[1,2,0,0],[2,3,0,0],[1,0,0,0],[0,1,0,0]]

b_prim=np.array(list(map(int,input("Enter right-hand side values of the constraints ").split(" "))))

#Taking sign 
res=[]
for i in range(len(A_prim)): 
  r=str(input(f"Enter Signs  (<=) ,(>=) or (=) for constraint {i+1} :"))
  res.append(r)


    
#Changing it into standard form
for i in range(len(res)):
  if res[i] == '<=':
    continue
  elif res[i] == '>=':
        A_prim[i,:] = A_prim[i,:]*(-1)
        res[i] = '<='
        b_prim[i] = b_prim[i]*(-1)

  elif res[i] == '=':
        A_prim[i,:] = A_prim[i,:]
        res[i]='<='
        A_prim = np.insert(A_prim, A_prim.shape[1],(A_prim[i,:])*(-1), axis=0)
        res.append('<=')
        b_prim = np.insert(b_prim, b_prim.shape[0],(b_prim[i])*(-1))

# #Type "nn" for non negative(>=)  and type "un" for  unrestricted
# for j in range(len(A_prim)):
#     r = str(input(f"Enter nn for non negative and un for unrestricted x{j+1} is :"))
#     if r== 'nn':
#       continue
#     elif r=="un":
#       X0 =np.array(A_prim[:,j])
#       A_prim = np.hstack((A_prim,X0))
     


Enter number of constraint in primal problem :3
Enter coefficients of the objective function :5 2 7
Enter constrain1 seprated with spaces :3 5 2
Enter constrain2 seprated with spaces :1 2 3
Enter constrain3 seprated with spaces :2 1 4
Enter right-hand side values of the constraints 12 8 5
Enter Signs  (<=) ,(>=) or (=) for constraint 1 :>=
Enter Signs  (<=) ,(>=) or (=) for constraint 2 :<=
Enter Signs  (<=) ,(>=) or (=) for constraint 3 :=


In [ ]:
#After changing it to the standard form 
print("Matrix A :",A_prim)
print()
print("b  :",b_prim)
print()
print("c :",c_prim)
print()
print("sign :",res)


Matrix A : [[-3 -5 -2]
 [ 1  2  3]
 [ 2  1  4]
 [-2 -1 -4]]

b  : [-12   8   5  -5]

c : [5 2 7]

sign : ['<=', '<=', '<=', '<=']


In [ ]:
def prim_to_dual(c_prim,A_prim,b_prim):
    

    
    #For maximisation problem and for slack variable and variables are greater equal zero
    #1. Define the number of decision variables and constraints in the primal problem and dual problem.
    dv_prim= len(c_prim)
    cons_prim =len(A_prim)

    dv_dual = len(b_prim)
    cons_prim = len(c_prim)
    
    

                           
    #2. Defining the coefficient matrix A_dual for the dual problem as the transpose of the coefficient matrix A for the primal problem.
    A_dual=A_prim.T
    print("Matrix A_dual :",A_dual)

    #3Defining the objective coefficient vector c_dual for the dual problem as the list of constants on the right-hand side of each primal constraint.
    c_dual = b_prim.T
    print("Decision variable coefficient for dual :",c_dual)

    #4.Define the right-hand side vector b_dual for the dual problem as the list of coefficients of the decision variables in the primal objective function.
    b_dual = c_prim.T
    print("Right hand side vector for dual problem :",b_dual)
    
prim_to_dual(c_prim,A_prim,b_prim)


Matrix A_dual : [[-3  1  2 -2]
 [-5  2  1 -1]
 [-2  3  4 -4]]
Decision variable coefficient for dual : [-12   8   5  -5]
Right hand side vector for dual problem : [5 2 7]
